when: << pipeline.parameters.run-flutter-workflow >>
jobs:
  - test-flutter
  - analyze-flutter
#  - integration-test-flutter-ios: # TODO: Fix, failing
#      filters:
#        branches:
#          only:
#            - main
#  - integration-test-flutter-macos: # TODO: Fix, failing
#      filters:
#        branches:
#          only:
#            - main
#  - integration-test-flutter-linux # TODO: Fix, failing
#  - integration-test-flutter-windows # TODO: Fix, failing
#  - integration-test-flutter-android # TODO: Fix, failing
